# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Dan Kondratyuk
tagline:          'Recursion is Recursive'
description:      'Elements of Programming and Machine Learning'
url:              https://dankondratyuk.com

author:
  name:           'Dan Kondratyuk'
  url:            https://dankondratyuk.com

paginate:         10

# Default vars
defaults:
  # Author info
  - scope:
      path: ''
    values:
      author: 'Dan Kondratyuk'
      avatar: '/public/img/dan-stencil-portrait-400x400.png'

# Custom vars
version:          1.2.0
github:
  repo:           https://github.com/hyperparticle/hyperparticle.github.io

# Gems
plugins: [jekyll-paginate]

# Directories
exclude: ["vendor", "bin"]
