# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyperparticle
tagline:          'Recursion is recursive'
description:      'Recursion is recursive'
url:              http://hyperparticle.com

author:
  name:           'Dan Kondratyuk'
  url:            https://twitter.com/hyperparticle

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hyperparticle/hyperparticle.github.io
