# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyperparticle
tagline:          'Recursion is recursive'
description:      'Dan Kondratyuk\'s website'
url:              https://hyperparticle.com

author:
  name:           'Dan Kondratyuk'
  url:            https://hyperparticle.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hyperparticle/hyperparticle.github.io

# Gems
gems: [jekyll-paginate]