# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyperparticle
tagline:          'Recursion is recursive'
description:      'A personal website'
url:              https://hyperparticle.com

author:
  name:           'Dan Kondratyuk'
  url:            https://hyperparticle.com

paginate:         5

# Default vars
defaults:
  # Post comments
  - scope:
      path: '' # All files in the project
      type: 'post'
    values:
      comments: true
  # Author info
  - scope:
      path: ''
    values:
      author: 'Dan Kondratyuk'
      avatar: '/public/img/dan-stencil-portrait-400x400.png'

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/hyperparticle/hyperparticle.github.io

# Gems
gems: [jekyll-paginate]